UNIT u_archivo_registros;
{$ CODEPAGE UTF8}
INTERFACE
CONST
RUTA= 'C:\Archivos\ARCHIVO_REGISTRO.DAT';
TYPE

T_DATO = record
         Nombre:string[20];
         Telefono:string[10];
         N_consulta:INTEGER;
end;

T_ARCHIVO = FILE OF T_DATO;

PROCEDURE CREAR(VAR ARCH:T_ARCHIVO);
PROCEDURE ABRIR(VAR ARCH:T_ARCHIVO);
PROCEDURE CERRAR(VAR ARCH:T_ARCHIVO);

IMPLEMENTATION

PROCEDURE CREAR(VAR ARCH:T_ARCHIVO);
 BEGIN
  ASSIGN(ARCH,RUTA);
  REWRITE(ARCH);
 END;
PROCEDURE ABRIR(VAR ARCH:T_ARCHIVO);
 BEGIN
  ASSIGN(ARCH,RUTA);
  RESET(ARCH);
 END;

PROCEDURE CERRAR(VAR ARCH:T_ARCHIVO);
 BEGIN
  CLOSE(ARCH);
 END;
end.
